
influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  volumes:
    - /srv/docker/influxdb/data:/var/lib/influxdb

grafana:
  image: grafana/grafana
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
  volumes:
    - /srv/docker/grafana/data:/var/lib/grafana


